const data = [
  {
    id: 1,
    fullName: "Vick Sutcliffe",
    avatar: "https://robohash.org/noncommodiet.png?size=50x50&set=set1",
    university: "Baker College of Flint",
    department: "Business Development",
  },
  {
    id: 2,
    fullName: "Estell Murfin",
    avatar: "https://robohash.org/sitlaboresit.png?size=50x50&set=set1",
    university: "Medaille College",
    department: "Product Management",
  },
  {
    id: 3,
    fullName: "Engelbert Sievewright",
    avatar: "https://robohash.org/sedetvoluptatem.png?size=50x50&set=set1",
    university: "South University of Science and Technology of China ",
    department: "Research and Development",
  },
  {
    id: 4,
    fullName: "Marje Nosworthy",
    avatar: "https://robohash.org/earumestamet.png?size=50x50&set=set1",
    university: "Aljouf University",
    department: "Accounting",
  },
  {
    id: 5,
    fullName: "Willow Bremmell",
    avatar: "https://robohash.org/abquiut.png?size=50x50&set=set1",
    university: "Trent University",
    department: "Engineering",
  },
  {
    id: 6,
    fullName: "Hussein Sunderland",
    avatar: "https://robohash.org/harumametet.png?size=50x50&set=set1",
    university: "Sultan Mizan Zainal Abidin Polytechnic",
    department: "Product Management",
  },
  {
    id: 7,
    fullName: "Ophelia Dangl",
    avatar: "https://robohash.org/sapienteeosnatus.png?size=50x50&set=set1",
    university: "Doho University",
    department: "Human Resources",
  },
  {
    id: 8,
    fullName: "Bridie Scandrett",
    avatar: "https://robohash.org/etvoluptasvoluptate.png?size=50x50&set=set1",
    university: "North Georgia College",
    department: "Sales",
  },
  {
    id: 9,
    fullName: "Mateo Morkham",
    avatar: "https://robohash.org/inquiadipisci.png?size=50x50&set=set1",
    university: "Rissho University",
    department: "Legal",
  },
  {
    id: 10,
    fullName: "Dyan Sullivan",
    avatar: "https://robohash.org/nisisititaque.png?size=50x50&set=set1",
    university: "Northcentral University",
    department: "Accounting",
  },
  {
    id: 11,
    fullName: "Lesley Wasmuth",
    avatar: "https://robohash.org/vitaeremea.png?size=50x50&set=set1",
    university: "Jacksonville State University",
    department: "Sales",
  },
  {
    id: 12,
    fullName: "Morie MacKall",
    avatar: "https://robohash.org/blanditiisatquesaepe.png?size=50x50&set=set1",
    university: "Cagayan State University",
    department: "Engineering",
  },
  {
    id: 13,
    fullName: "Lainey La Vigne",
    avatar: "https://robohash.org/vitaeodionon.png?size=50x50&set=set1",
    university: "Mohammad Ali Jinnah University",
    department: "Business Development",
  },
  {
    id: 14,
    fullName: "Carlo Bozier",
    avatar: "https://robohash.org/pariaturnesciuntest.png?size=50x50&set=set1",
    university: "National College of Ireland",
    department: "Business Development",
  },
  {
    id: 15,
    fullName: "Rick Daniel",
    avatar:
      "https://robohash.org/debitisvoluptatesdolorem.png?size=50x50&set=set1",
    university: "Dong-A University",
    department: "Business Development",
  },
  {
    id: 16,
    fullName: "Carlie Parish",
    avatar:
      "https://robohash.org/pariaturvoluptasvelit.png?size=50x50&set=set1",
    university: "Miami Dade College",
    department: "Business Development",
  },
  {
    id: 17,
    fullName: "Thain Darrington",
    avatar: "https://robohash.org/estetcommodi.png?size=50x50&set=set1",
    university: "Université de Pau et des Pays de l'Adour",
    department: "Business Development",
  },
  {
    id: 18,
    fullName: "Julie Mulchrone",
    avatar: "https://robohash.org/quidemcumnesciunt.png?size=50x50&set=set1",
    university: "Wageningen University",
    department: "Accounting",
  },
  {
    id: 19,
    fullName: "Chelsae Torrent",
    avatar: "https://robohash.org/eumestofficia.png?size=50x50&set=set1",
    university: "Ningbo University of Technology",
    department: "Research and Development",
  },
  {
    id: 20,
    fullName: "Cheryl Jefferd",
    avatar: "https://robohash.org/veritatisvelsequi.png?size=50x50&set=set1",
    university:
      "Higher School o Business/National Louis University(WSB/NLU) in Nowy Sacz",
    department: "Business Development",
  },
  {
    id: 21,
    fullName: "Meryl Salery",
    avatar: "https://robohash.org/suntnostrummagni.png?size=50x50&set=set1",
    university: "Mongolian State University of Arts and Culture",
    department: "Accounting",
  },
  {
    id: 22,
    fullName: "Pamelina Gligoraci",
    avatar: "https://robohash.org/dolordolorexcepturi.png?size=50x50&set=set1",
    university: "Clark University",
    department: "Engineering",
  },
  {
    id: 23,
    fullName: "Randolf Chinge",
    avatar: "https://robohash.org/autfugaest.png?size=50x50&set=set1",
    university: "Johns Hopkins University, SAIS Bologna Center",
    department: "Sales",
  },
  {
    id: 24,
    fullName: "Shaina Widmoor",
    avatar: "https://robohash.org/etvoluptatemillo.png?size=50x50&set=set1",
    university: "Institute of Teachers Education, Sultan Abdul Halim",
    department: "Training",
  },
  {
    id: 25,
    fullName: "Zora Gherarducci",
    avatar: "https://robohash.org/omnisearumnihil.png?size=50x50&set=set1",
    university: "Minia University",
    department: "Legal",
  },
  {
    id: 26,
    fullName: "Sheppard Coaten",
    avatar: "https://robohash.org/quoconsequunturminus.png?size=50x50&set=set1",
    university: "Washburn University",
    department: "Marketing",
  },
  {
    id: 27,
    fullName: "Powell Mitchener",
    avatar: "https://robohash.org/nonnostrumesse.png?size=50x50&set=set1",
    university: "Universidad Nacional José Faustino Sánchez Carrión",
    department: "Support",
  },
  {
    id: 28,
    fullName: "Krystle Finlan",
    avatar:
      "https://robohash.org/corporisexpeditaassumenda.png?size=50x50&set=set1",
    university: "Shanghai University of Engineering Science",
    department: "Product Management",
  },
  {
    id: 29,
    fullName: "Berty Duckit",
    avatar: "https://robohash.org/ducimusullamculpa.png?size=50x50&set=set1",
    university: "University of Mauritius",
    department: "Training",
  },
  {
    id: 30,
    fullName: "Briney Sword",
    avatar: "https://robohash.org/consequaturnihilnon.png?size=50x50&set=set1",
    university: "Universidad Autónoma del Estado de Morelos",
    department: "Research and Development",
  },
  {
    id: 31,
    fullName: "Cornelia Schofield",
    avatar: "https://robohash.org/modiautmolestias.png?size=50x50&set=set1",
    university: "Universidade Lusiada",
    department: "Legal",
  },
  {
    id: 32,
    fullName: "Brita Garatty",
    avatar: "https://robohash.org/distinctioidet.png?size=50x50&set=set1",
    university: "Zagazig University",
    department: "Services",
  },
  {
    id: 33,
    fullName: "Robin Gronow",
    avatar: "https://robohash.org/estnemoquisquam.png?size=50x50&set=set1",
    university: "University of Nijenrode",
    department: "Human Resources",
  },
  {
    id: 34,
    fullName: "Kakalina Etheredge",
    avatar: "https://robohash.org/etveleum.png?size=50x50&set=set1",
    university: "Universidad Central del Este",
    department: "Training",
  },
  {
    id: 35,
    fullName: "Decca Gullan",
    avatar: "https://robohash.org/dolorenonratione.png?size=50x50&set=set1",
    university: "Western State College",
    department: "Research and Development",
  },
  {
    id: 36,
    fullName: "Che Oakley",
    avatar: "https://robohash.org/esteoscorrupti.png?size=50x50&set=set1",
    university: "Trinity Theological Seminary",
    department: "Sales",
  },
  {
    id: 37,
    fullName: "Kalil Bes",
    avatar: "https://robohash.org/remquiadolor.png?size=50x50&set=set1",
    university: "Universidade Federal do Acre",
    department: "Training",
  },
  {
    id: 38,
    fullName: "Giacopo Fountian",
    avatar: "https://robohash.org/temporequieum.png?size=50x50&set=set1",
    university: "Chikushi Jogakuen University",
    department: "Business Development",
  },
  {
    id: 39,
    fullName: "Hillary Morratt",
    avatar: "https://robohash.org/commodiquidembeatae.png?size=50x50&set=set1",
    university:
      "Hochschule Wismar, Fachhochschule für Technik, Wirtschaft und Gestaltung",
    department: "Sales",
  },
  {
    id: 40,
    fullName: "Harwilll Skippon",
    avatar: "https://robohash.org/consecteturtotamaut.png?size=50x50&set=set1",
    university: "Groupe Sup de Co Montpellier",
    department: "Business Development",
  },
  {
    id: 41,
    fullName: "Peri Lamp",
    avatar: "https://robohash.org/necessitatibusidsit.png?size=50x50&set=set1",
    university: "Islamic University of Medinah",
    department: "Engineering",
  },
  {
    id: 42,
    fullName: "Elisha Sommerled",
    avatar:
      "https://robohash.org/voluptatemmaiorespossimus.png?size=50x50&set=set1",
    university: "Shanghai Television University",
    department: "Accounting",
  },
  {
    id: 43,
    fullName: "Gian Dahlbom",
    avatar: "https://robohash.org/eaautqui.png?size=50x50&set=set1",
    university: "Igbinedion University",
    department: "Legal",
  },
  {
    id: 44,
    fullName: "Rob Barrass",
    avatar: "https://robohash.org/aperiamblanditiisad.png?size=50x50&set=set1",
    university: "State Maritine Academy",
    department: "Business Development",
  },
  {
    id: 45,
    fullName: "Ashil Groger",
    avatar: "https://robohash.org/delenitietomnis.png?size=50x50&set=set1",
    university: "Cleveland Institute of Art",
    department: "Sales",
  },
  {
    id: 46,
    fullName: "Carleton Waleran",
    avatar: "https://robohash.org/officianondolorem.png?size=50x50&set=set1",
    university: "Tula State University",
    department: "Business Development",
  },
  {
    id: 47,
    fullName: "Clayborn Hutt",
    avatar: "https://robohash.org/consequaturetnon.png?size=50x50&set=set1",
    university: "Rak Medical & Health Sciences University",
    department: "Legal",
  },
  {
    id: 48,
    fullName: "Damara Rottcher",
    avatar: "https://robohash.org/accusantiumvitaeab.png?size=50x50&set=set1",
    university: "North Maharashtra University",
    department: "Research and Development",
  },
  {
    id: 49,
    fullName: "Shepherd Laden",
    avatar: "https://robohash.org/atvoluptatemnihil.png?size=50x50&set=set1",
    university: "Warsaw School of Social Psychology",
    department: "Legal",
  },
  {
    id: 50,
    fullName: "Min Tidder",
    avatar: "https://robohash.org/adaliquidnatus.png?size=50x50&set=set1",
    university: "Mercer University, Cecil B. Day Campus",
    department: "Marketing",
  },
  {
    id: 51,
    fullName: "Ky Antoniat",
    avatar:
      "https://robohash.org/utconsecteturconsequatur.png?size=50x50&set=set1",
    university: "Sekolah Tinggi Akuntansi Negara (STAN)",
    department: "Research and Development",
  },
  {
    id: 52,
    fullName: "Faustina Rosewarne",
    avatar: "https://robohash.org/estetdolores.png?size=50x50&set=set1",
    university: "Polytechnic Institute of Milan",
    department: "Legal",
  },
  {
    id: 53,
    fullName: "Avigdor Ceney",
    avatar: "https://robohash.org/veniamdeseruntamet.png?size=50x50&set=set1",
    university: "KDU College Sdn Bhd",
    department: "Services",
  },
  {
    id: 54,
    fullName: "Tyler Bleakman",
    avatar: "https://robohash.org/etnonmagnam.png?size=50x50&set=set1",
    university: "University of the Visayas",
    department: "Human Resources",
  },
  {
    id: 55,
    fullName: "Fabiano Hellewell",
    avatar: "https://robohash.org/quodquivoluptate.png?size=50x50&set=set1",
    university: "Evangelische Hochschule für Soziale Arbeit Dresden (FH)",
    department: "Product Management",
  },
  {
    id: 56,
    fullName: "Stanton Plevey",
    avatar: "https://robohash.org/quasiustoearum.png?size=50x50&set=set1",
    university: "Dartmouth College",
    department: "Engineering",
  },
  {
    id: 57,
    fullName: "Evyn Nazaret",
    avatar:
      "https://robohash.org/assumendareprehenderitnon.png?size=50x50&set=set1",
    university: "Southwest University of Finance and Economics",
    department: "Research and Development",
  },
  {
    id: 58,
    fullName: "Gayelord Grieve",
    avatar: "https://robohash.org/quasautmaiores.png?size=50x50&set=set1",
    university: "Centre d'Etudes Supérieures Industrielles Paris",
    department: "Legal",
  },
  {
    id: 59,
    fullName: "Tabina Perse",
    avatar: "https://robohash.org/aspernaturdictaeius.png?size=50x50&set=set1",
    university: "The University of Nottingham Ningbo China",
    department: "Accounting",
  },
  {
    id: 60,
    fullName: "Maryl Roughan",
    avatar: "https://robohash.org/sintvitaesed.png?size=50x50&set=set1",
    university: "St. Petersburg State Cinema and TV University",
    department: "Marketing",
  },
  {
    id: 61,
    fullName: "Ashbey Spritt",
    avatar: "https://robohash.org/rerumipsamab.png?size=50x50&set=set1",
    university: "Muthesius-Hochschule, Fachhochschule für Kunst und Gestaltung",
    department: "Training",
  },
  {
    id: 62,
    fullName: "Billy Ogg",
    avatar:
      "https://robohash.org/solutanecessitatibusnam.png?size=50x50&set=set1",
    university: "St. Norbert College",
    department: "Support",
  },
  {
    id: 63,
    fullName: "Jan Smallbone",
    avatar: "https://robohash.org/fugittemporibusea.png?size=50x50&set=set1",
    university: "American University of the Caribbean, School of Medicine",
    department: "Business Development",
  },
  {
    id: 64,
    fullName: "Bryce Vakhrushin",
    avatar:
      "https://robohash.org/corporisquoaspernatur.png?size=50x50&set=set1",
    university: "University of Calabar",
    department: "Engineering",
  },
  {
    id: 65,
    fullName: "Maure Daniaud",
    avatar: "https://robohash.org/officiaidaperiam.png?size=50x50&set=set1",
    university: "United States Air Force Academy",
    department: "Accounting",
  },
  {
    id: 66,
    fullName: "Callean Perone",
    avatar:
      "https://robohash.org/mollitiaconsecteturdeserunt.png?size=50x50&set=set1",
    university: "Faculdade Integradas do Ceará",
    department: "Business Development",
  },
  {
    id: 67,
    fullName: "Carmita Kolodziej",
    avatar: "https://robohash.org/autemestquis.png?size=50x50&set=set1",
    university: "Kumasi Polytechnic ",
    department: "Human Resources",
  },
  {
    id: 68,
    fullName: "Julina Gawke",
    avatar:
      "https://robohash.org/eligendivitaedignissimos.png?size=50x50&set=set1",
    university: "Troy University, Troy",
    department: "Engineering",
  },
  {
    id: 69,
    fullName: "Jere Morde",
    avatar: "https://robohash.org/molestiasquisquamet.png?size=50x50&set=set1",
    university: "Technological University (Kalay)",
    department: "Research and Development",
  },
  {
    id: 70,
    fullName: "Norrie Bugg",
    avatar:
      "https://robohash.org/quiaconsequunturquaerat.png?size=50x50&set=set1",
    university: "Carl von Ossietzky Universität Oldenburg",
    department: "Accounting",
  },
  {
    id: 71,
    fullName: "Mina Swyndley",
    avatar: "https://robohash.org/omnissintquasi.png?size=50x50&set=set1",
    university: "Universidade Católica de Angola",
    department: "Accounting",
  },
  {
    id: 72,
    fullName: "Alessandra Ibbott",
    avatar: "https://robohash.org/auteosipsum.png?size=50x50&set=set1",
    university: "Instituto Politécnico de Tomar",
    department: "Product Management",
  },
  {
    id: 73,
    fullName: "Carilyn Lillyman",
    avatar:
      "https://robohash.org/sintconsequaturaliquam.png?size=50x50&set=set1",
    university: "Yazd University",
    department: "Business Development",
  },
  {
    id: 74,
    fullName: "Prentice Sneezum",
    avatar: "https://robohash.org/veniamipsaea.png?size=50x50&set=set1",
    university: "Lamar University - Port Arthur",
    department: "Marketing",
  },
  {
    id: 75,
    fullName: "Constance Cumbes",
    avatar: "https://robohash.org/undequamest.png?size=50x50&set=set1",
    university: "Universidad Politecnica de Puerto Rico",
    department: "Accounting",
  },
  {
    id: 76,
    fullName: "Tadd Starten",
    avatar: "https://robohash.org/debitisquiesse.png?size=50x50&set=set1",
    university: "St. Clair College",
    department: "Support",
  },
  {
    id: 77,
    fullName: "Adams Richardes",
    avatar: "https://robohash.org/quidoloresducimus.png?size=50x50&set=set1",
    university: "Northwestern University of the Philippines",
    department: "Sales",
  },
  {
    id: 78,
    fullName: "Mariette Birdwistle",
    avatar: "https://robohash.org/sitdoloremratione.png?size=50x50&set=set1",
    university: "Istanbul Kultur University",
    department: "Product Management",
  },
  {
    id: 79,
    fullName: "Beryl Schubert",
    avatar: "https://robohash.org/faceredistinctionon.png?size=50x50&set=set1",
    university: "Athens University of Economics and Business",
    department: "Legal",
  },
  {
    id: 80,
    fullName: "Clay Doore",
    avatar:
      "https://robohash.org/illumnostrumvoluptatem.png?size=50x50&set=set1",
    university: "Ecole Supérieure de Commerce de Lille",
    department: "Services",
  },
  {
    id: 81,
    fullName: "Adolphe Guilbert",
    avatar: "https://robohash.org/ullamdolorvoluptatem.png?size=50x50&set=set1",
    university: "Hubei University",
    department: "Research and Development",
  },
  {
    id: 82,
    fullName: "Des Kent",
    avatar:
      "https://robohash.org/itaquevoluptasvoluptatem.png?size=50x50&set=set1",
    university: "Rochester Institute of Technology, Dubai",
    department: "Human Resources",
  },
  {
    id: 83,
    fullName: "Rosene Ibbitson",
    avatar: "https://robohash.org/cumillonumquam.png?size=50x50&set=set1",
    university: "Eugene Bible College",
    department: "Services",
  },
  {
    id: 84,
    fullName: "Teador Caskie",
    avatar: "https://robohash.org/autemrepellatanimi.png?size=50x50&set=set1",
    university: "Auckland University of Technology",
    department: "Product Management",
  },
  {
    id: 85,
    fullName: "Massimo Baddam",
    avatar:
      "https://robohash.org/reprehenderitperspiciatisaperiam.png?size=50x50&set=set1",
    university: "University of Wales, Newport",
    department: "Sales",
  },
  {
    id: 86,
    fullName: "Huntlee Haburne",
    avatar: "https://robohash.org/etnequeeos.png?size=50x50&set=set1",
    university: "University of Medicine 1, Yangon",
    department: "Engineering",
  },
  {
    id: 87,
    fullName: "Florenza Hawse",
    avatar: "https://robohash.org/utsedreiciendis.png?size=50x50&set=set1",
    university: "Showa University",
    department: "Sales",
  },
  {
    id: 88,
    fullName: "Toddie Hlavac",
    avatar: "https://robohash.org/accusamusindelectus.png?size=50x50&set=set1",
    university: "Aston University",
    department: "Sales",
  },
  {
    id: 89,
    fullName: "Lev Edds",
    avatar: "https://robohash.org/isteaspernaturautem.png?size=50x50&set=set1",
    university: "Asbury College",
    department: "Engineering",
  },
  {
    id: 90,
    fullName: "Graig Millbank",
    avatar: "https://robohash.org/remiustoest.png?size=50x50&set=set1",
    university: "Al-Nasser University",
    department: "Engineering",
  },
  {
    id: 91,
    fullName: "Pearle Beakes",
    avatar:
      "https://robohash.org/voluptatemdolordoloribus.png?size=50x50&set=set1",
    university: "Universidad del Museo Social Argentino",
    department: "Research and Development",
  },
  {
    id: 92,
    fullName: "Pepita McCulley",
    avatar: "https://robohash.org/quisquamautquis.png?size=50x50&set=set1",
    university: "Joetsu University of Education",
    department: "Engineering",
  },
  {
    id: 93,
    fullName: "Cosme Snare",
    avatar:
      "https://robohash.org/distinctiocorporisdeserunt.png?size=50x50&set=set1",
    university: "Université Bordeaux I",
    department: "Services",
  },
  {
    id: 94,
    fullName: "Nerty Munroe",
    avatar: "https://robohash.org/adipiscivelest.png?size=50x50&set=set1",
    university: "Glasgow School of Art",
    department: "Accounting",
  },
  {
    id: 95,
    fullName: "Abner Sparey",
    avatar: "https://robohash.org/utsedaccusantium.png?size=50x50&set=set1",
    university: "Universidad Nacional de Ucayali",
    department: "Marketing",
  },
  {
    id: 96,
    fullName: "Karee Sousa",
    avatar: "https://robohash.org/quoeumsunt.png?size=50x50&set=set1",
    university: "New York Institute of Technology",
    department: "Support",
  },
  {
    id: 97,
    fullName: "Yardley MacGuffie",
    avatar:
      "https://robohash.org/estconsequuntureveniet.png?size=50x50&set=set1",
    university: "Urmia University of Medical Sciences",
    department: "Support",
  },
  {
    id: 98,
    fullName: "Kerk Whapples",
    avatar:
      "https://robohash.org/consequaturitaqueiusto.png?size=50x50&set=set1",
    university: "University of Toronto",
    department: "Engineering",
  },
  {
    id: 99,
    fullName: "Nealson Bilton",
    avatar: "https://robohash.org/quiaiustoet.png?size=50x50&set=set1",
    university: "Ryerson Polytechnic University",
    department: "Services",
  },
  {
    id: 100,
    fullName: "Elene Borne",
    avatar: "https://robohash.org/laboreinipsum.png?size=50x50&set=set1",
    university: "Tamil Nadu Agricultural University",
    department: "Accounting",
  },
  {
    id: 101,
    fullName: "Vale Manoelli",
    avatar: "https://robohash.org/adipisciaperiamipsam.png?size=50x50&set=set1",
    university: "Nisho Gakusha University",
    department: "Legal",
  },
  {
    id: 102,
    fullName: "Joshuah Pettifer",
    avatar: "https://robohash.org/evenietmaioresvelit.png?size=50x50&set=set1",
    university: "Clark University",
    department: "Training",
  },
  {
    id: 103,
    fullName: "Lynett Hinks",
    avatar: "https://robohash.org/culpaautomnis.png?size=50x50&set=set1",
    university: "Universidad Privada de Tacna",
    department: "Services",
  },
  {
    id: 104,
    fullName: "Randi Durrant",
    avatar: "https://robohash.org/delenitisuntomnis.png?size=50x50&set=set1",
    university: "University of Chittagong",
    department: "Human Resources",
  },
  {
    id: 105,
    fullName: "Georgianna Spyer",
    avatar: "https://robohash.org/etiustofacere.png?size=50x50&set=set1",
    university: "Southwestern College Santa Fe",
    department: "Marketing",
  },
  {
    id: 106,
    fullName: "Jeromy Ivkovic",
    avatar: "https://robohash.org/ipsamveroillo.png?size=50x50&set=set1",
    university: "Universidade do Rio de Janeiro",
    department: "Accounting",
  },
  {
    id: 107,
    fullName: "Tiebout Peel",
    avatar: "https://robohash.org/etatquelaborum.png?size=50x50&set=set1",
    university: "Nicola Valley Institute of Technology",
    department: "Engineering",
  },
  {
    id: 108,
    fullName: "Elbertina Carbin",
    avatar:
      "https://robohash.org/facerevelittemporibus.png?size=50x50&set=set1",
    university: "Murni Nursing College",
    department: "Human Resources",
  },
  {
    id: 109,
    fullName: "Germana Derry",
    avatar: "https://robohash.org/cumquemolestiaemagni.png?size=50x50&set=set1",
    university: "Institut National des Sciences Appliquées de Rouen",
    department: "Product Management",
  },
  {
    id: 110,
    fullName: "Rick Bitchener",
    avatar: "https://robohash.org/addoloremet.png?size=50x50&set=set1",
    university: "Beijing University of Posts and Telecommunications",
    department: "Sales",
  },
  {
    id: 111,
    fullName: "Edvard Conachie",
    avatar:
      "https://robohash.org/quiaarchitectolaudantium.png?size=50x50&set=set1",
    university: "Medical University Pleven",
    department: "Human Resources",
  },
  {
    id: 112,
    fullName: "Estella Woolveridge",
    avatar: "https://robohash.org/harumetest.png?size=50x50&set=set1",
    university: "Hofstra University",
    department: "Human Resources",
  },
  {
    id: 113,
    fullName: "Frances Pinkney",
    avatar: "https://robohash.org/eautdistinctio.png?size=50x50&set=set1",
    university: "Grinnell College",
    department: "Engineering",
  },
  {
    id: 114,
    fullName: "Berry Bartleet",
    avatar: "https://robohash.org/atmagnamdolor.png?size=50x50&set=set1",
    university: "Hijiyama University",
    department: "Accounting",
  },
  {
    id: 115,
    fullName: "Gunter Buckenham",
    avatar: "https://robohash.org/omnisestmollitia.png?size=50x50&set=set1",
    university: "Penang International Dental College",
    department: "Legal",
  },
  {
    id: 116,
    fullName: "Katerina Gilardone",
    avatar: "https://robohash.org/porroestexpedita.png?size=50x50&set=set1",
    university: "Gyeongju University",
    department: "Services",
  },
  {
    id: 117,
    fullName: "Giulio Buche",
    avatar: "https://robohash.org/namesteveniet.png?size=50x50&set=set1",
    university: "Russian State Medical University",
    department: "Support",
  },
  {
    id: 118,
    fullName: "Kriste Huitt",
    avatar:
      "https://robohash.org/omnisquaeperspiciatis.png?size=50x50&set=set1",
    university: "Jilin University of Technology",
    department: "Human Resources",
  },
  {
    id: 119,
    fullName: "Rolando Esby",
    avatar:
      "https://robohash.org/doloreslaudantiumblanditiis.png?size=50x50&set=set1",
    university: "Universiti Kuala Lumpur",
    department: "Engineering",
  },
  {
    id: 120,
    fullName: "Pepito Casassa",
    avatar:
      "https://robohash.org/temporaquidemvoluptatibus.png?size=50x50&set=set1",
    university: "Hyogo College of Medicine",
    department: "Legal",
  },
  {
    id: 121,
    fullName: "Kassie Danilewicz",
    avatar: "https://robohash.org/excepturietsunt.png?size=50x50&set=set1",
    university: "Universidad Privada del Valle",
    department: "Training",
  },
  {
    id: 122,
    fullName: "Minor Dyka",
    avatar: "https://robohash.org/vitaecorruptifugit.png?size=50x50&set=set1",
    university: "Sree Sankaracharya University of Sanskrit",
    department: "Human Resources",
  },
  {
    id: 123,
    fullName: "Jens Swatridge",
    avatar: "https://robohash.org/remaliquiddolores.png?size=50x50&set=set1",
    university: "Monash University",
    department: "Engineering",
  },
  {
    id: 124,
    fullName: "Winifred Florence",
    avatar:
      "https://robohash.org/perspiciatisnisiducimus.png?size=50x50&set=set1",
    university: "Universität Potsdam",
    department: "Business Development",
  },
  {
    id: 125,
    fullName: "Sonnie Avon",
    avatar: "https://robohash.org/etsintminus.png?size=50x50&set=set1",
    university: "International East-European University",
    department: "Marketing",
  },
  {
    id: 126,
    fullName: "Alex Stanborough",
    avatar: "https://robohash.org/nulladolorcupiditate.png?size=50x50&set=set1",
    university: "Massachusetts School of Professional Psychology",
    department: "Business Development",
  },
  {
    id: 127,
    fullName: "Cammy Dolling",
    avatar: "https://robohash.org/liberoevenietquis.png?size=50x50&set=set1",
    university: "Kazak National Technical University",
    department: "Human Resources",
  },
  {
    id: 128,
    fullName: "Krysta Yegorchenkov",
    avatar: "https://robohash.org/possimusdelectusaut.png?size=50x50&set=set1",
    university: "Khulna University",
    department: "Services",
  },
  {
    id: 129,
    fullName: "Celestyna Shurey",
    avatar:
      "https://robohash.org/eaquedoloribussimilique.png?size=50x50&set=set1",
    university: "Cleveland Chiropractic College, Los Angeles",
    department: "Product Management",
  },
  {
    id: 130,
    fullName: "Marta Sowley",
    avatar: "https://robohash.org/nobiscumfugit.png?size=50x50&set=set1",
    university: "Continental Theological Seminary",
    department: "Legal",
  },
  {
    id: 131,
    fullName: "Candida Bradtke",
    avatar: "https://robohash.org/temporaidomnis.png?size=50x50&set=set1",
    university: "Royal Roads University",
    department: "Accounting",
  },
  {
    id: 132,
    fullName: "Aggi Croote",
    avatar: "https://robohash.org/consequaturutvel.png?size=50x50&set=set1",
    university: "Quaid-i-Azam University",
    department: "Training",
  },
  {
    id: 133,
    fullName: "Zorana Cairns",
    avatar: "https://robohash.org/quiaquaslaboriosam.png?size=50x50&set=set1",
    university: "Azerbaijan State Economic University",
    department: "Research and Development",
  },
  {
    id: 134,
    fullName: "Irene Stoller",
    avatar: "https://robohash.org/adautrecusandae.png?size=50x50&set=set1",
    university: "Universidad de Concepción del Uruguay",
    department: "Business Development",
  },
  {
    id: 135,
    fullName: "Lothaire Stair",
    avatar: "https://robohash.org/quiaanimiplaceat.png?size=50x50&set=set1",
    university: "Weizmann Institute of Science",
    department: "Business Development",
  },
  {
    id: 136,
    fullName: "Patton Mathivet",
    avatar: "https://robohash.org/nonearumbeatae.png?size=50x50&set=set1",
    university: "Aventis School of Management",
    department: "Services",
  },
  {
    id: 137,
    fullName: "Noellyn St Ledger",
    avatar: "https://robohash.org/eosvoluptasminima.png?size=50x50&set=set1",
    university: "Universität Bayreuth",
    department: "Business Development",
  },
  {
    id: 138,
    fullName: "Eadmund Ferrario",
    avatar: "https://robohash.org/vitaetemporaiusto.png?size=50x50&set=set1",
    university: "Virginia State University",
    department: "Research and Development",
  },
  {
    id: 139,
    fullName: "Martita Gandey",
    avatar: "https://robohash.org/voluptatesametid.png?size=50x50&set=set1",
    university: "Air Force Institute of Technology",
    department: "Sales",
  },
  {
    id: 140,
    fullName: "Junia Winger",
    avatar: "https://robohash.org/voluptasatquaerat.png?size=50x50&set=set1",
    university: "North Central College",
    department: "Accounting",
  },
  {
    id: 141,
    fullName: "Del Kaes",
    avatar:
      "https://robohash.org/veritatiseiusvoluptas.png?size=50x50&set=set1",
    university: "Chungnam National University",
    department: "Research and Development",
  },
  {
    id: 142,
    fullName: "Sofia Ramstead",
    avatar:
      "https://robohash.org/adipiscimagnamquisquam.png?size=50x50&set=set1",
    university: "Grenoble Ecole de Management",
    department: "Human Resources",
  },
  {
    id: 143,
    fullName: "Eduino Pywell",
    avatar: "https://robohash.org/rerumomnisnulla.png?size=50x50&set=set1",
    university: "University of Southern Maine",
    department: "Training",
  },
  {
    id: 144,
    fullName: "Reta Leve",
    avatar: "https://robohash.org/commodilaudantiumea.png?size=50x50&set=set1",
    university: "Quincy University",
    department: "Accounting",
  },
  {
    id: 145,
    fullName: "Webster Lound",
    avatar:
      "https://robohash.org/quasisimiliqueconsequatur.png?size=50x50&set=set1",
    university: "St. Xavier University",
    department: "Engineering",
  },
  {
    id: 146,
    fullName: "Megan Korneichik",
    avatar:
      "https://robohash.org/expeditaaccusantiumsapiente.png?size=50x50&set=set1",
    university: "Hiroshima University of Economics",
    department: "Research and Development",
  },
  {
    id: 147,
    fullName: "Netta Stetlye",
    avatar: "https://robohash.org/rerumomnisea.png?size=50x50&set=set1",
    university: "Holar University College",
    department: "Human Resources",
  },
  {
    id: 148,
    fullName: "Tina Sheardown",
    avatar:
      "https://robohash.org/possimusexcepturieaque.png?size=50x50&set=set1",
    university: "Limestone College",
    department: "Legal",
  },
  {
    id: 149,
    fullName: "Elias Giacopelo",
    avatar: "https://robohash.org/temporeremillum.png?size=50x50&set=set1",
    university: "Kocaeli University",
    department: "Training",
  },
  {
    id: 150,
    fullName: "Rozanna Winspire",
    avatar: "https://robohash.org/enimquodvoluptas.png?size=50x50&set=set1",
    university: "Indira Gandhi Institute of Medical Sciences",
    department: "Legal",
  },
  {
    id: 151,
    fullName: "Isabel Barhams",
    avatar: "https://robohash.org/maximererumnobis.png?size=50x50&set=set1",
    university: "Sumgait State University",
    department: "Marketing",
  },
  {
    id: 152,
    fullName: "Milly Colledge",
    avatar:
      "https://robohash.org/aliquamvoluptatesapiente.png?size=50x50&set=set1",
    university: "Universidad Autónoma de la Ciudad de México",
    department: "Marketing",
  },
  {
    id: 153,
    fullName: "Cori Birchett",
    avatar: "https://robohash.org/modieoset.png?size=50x50&set=set1",
    university: "Mahatma Jyotiba Phule Rohilkhand University Bareilly ",
    department: "Services",
  },
  {
    id: 154,
    fullName: "Andonis Nanuccioi",
    avatar:
      "https://robohash.org/necessitatibusminusrem.png?size=50x50&set=set1",
    university: "Sekolah Tinggi Akuntansi Negara (STAN)",
    department: "Product Management",
  },
  {
    id: 155,
    fullName: "Liliane Sibary",
    avatar: "https://robohash.org/nisieaqui.png?size=50x50&set=set1",
    university: "Minsk Institute of Management",
    department: "Legal",
  },
  {
    id: 156,
    fullName: "Gabriellia Wraxall",
    avatar:
      "https://robohash.org/rationequisvoluptatem.png?size=50x50&set=set1",
    university: "Universidad de Manizales",
    department: "Product Management",
  },
  {
    id: 157,
    fullName: "Stanislaw Baile",
    avatar: "https://robohash.org/quiquiaodio.png?size=50x50&set=set1",
    university: "Great Zimbabwe University",
    department: "Research and Development",
  },
  {
    id: 158,
    fullName: "Cheslie Di Giacomo",
    avatar:
      "https://robohash.org/quisquamnesciuntincidunt.png?size=50x50&set=set1",
    university: "University of Ottawa",
    department: "Training",
  },
  {
    id: 159,
    fullName: "Tanney Hanway",
    avatar:
      "https://robohash.org/consecteturinrepudiandae.png?size=50x50&set=set1",
    university: "Columbia College Hollywood",
    department: "Sales",
  },
  {
    id: 160,
    fullName: "Niko Hamnet",
    avatar:
      "https://robohash.org/repellendusfacilisfugiat.png?size=50x50&set=set1",
    university: "Universidade de Santa Cruz do Sul",
    department: "Business Development",
  },
  {
    id: 161,
    fullName: "Humbert Lyddyard",
    avatar: "https://robohash.org/quiisteculpa.png?size=50x50&set=set1",
    university: "Yanbian University of Science and Technology",
    department: "Sales",
  },
  {
    id: 162,
    fullName: "Alford Rozalski",
    avatar: "https://robohash.org/earumquirecusandae.png?size=50x50&set=set1",
    university:
      'Instituto Superior Minero Metalúrgico "Dr. Antonio Núñez Jiménez"',
    department: "Human Resources",
  },
  {
    id: 163,
    fullName: "Teresa Hambric",
    avatar:
      "https://robohash.org/porroexercitationemaut.png?size=50x50&set=set1",
    university: "Hyupsung University",
    department: "Support",
  },
  {
    id: 164,
    fullName: "Patrice Joriot",
    avatar: "https://robohash.org/maximesequiratione.png?size=50x50&set=set1",
    university: "Bratsk State Technical University",
    department: "Training",
  },
  {
    id: 165,
    fullName: "Gabby O'Lennachain",
    avatar: "https://robohash.org/explicabocumminima.png?size=50x50&set=set1",
    university: "Hvanneyri Agricultural University",
    department: "Legal",
  },
  {
    id: 166,
    fullName: "Sheena Burden",
    avatar:
      "https://robohash.org/consequaturquibusdamdeleniti.png?size=50x50&set=set1",
    university: "St. Petersburg State Marine Technical University",
    department: "Legal",
  },
  {
    id: 167,
    fullName: "Benton Concklin",
    avatar: "https://robohash.org/quibusdamexnam.png?size=50x50&set=set1",
    university: "Maltepe University",
    department: "Accounting",
  },
  {
    id: 168,
    fullName: "Norean Kobes",
    avatar: "https://robohash.org/illumquialiquid.png?size=50x50&set=set1",
    university: "Belmont Abbey College",
    department: "Product Management",
  },
  {
    id: 169,
    fullName: "Hynda Trayes",
    avatar:
      "https://robohash.org/quaedoloremvoluptatibus.png?size=50x50&set=set1",
    university: "Osaka University of Commerce",
    department: "Research and Development",
  },
  {
    id: 170,
    fullName: "Weston Pendall",
    avatar: "https://robohash.org/eaatqueconsectetur.png?size=50x50&set=set1",
    university: "Karlshochschule International University",
    department: "Services",
  },
  {
    id: 171,
    fullName: "Gaspard Daid",
    avatar: "https://robohash.org/autmaximeimpedit.png?size=50x50&set=set1",
    university: "International Kazakh-Turkish University",
    department: "Legal",
  },
  {
    id: 172,
    fullName: "Andy Pugsley",
    avatar: "https://robohash.org/sapienteenimquasi.png?size=50x50&set=set1",
    university: "Mbarara University of Science and Technology",
    department: "Engineering",
  },
  {
    id: 173,
    fullName: "Son Giannazzi",
    avatar: "https://robohash.org/quametnumquam.png?size=50x50&set=set1",
    university: "Universität Rostock",
    department: "Product Management",
  },
  {
    id: 174,
    fullName: "Reuben Slobom",
    avatar: "https://robohash.org/totamsitullam.png?size=50x50&set=set1",
    university: "Vaasa University of Applied Sciences",
    department: "Engineering",
  },
  {
    id: 175,
    fullName: "Faye Iorizzi",
    avatar: "https://robohash.org/autdelenitiexplicabo.png?size=50x50&set=set1",
    university: "Universidad de Cartago Florencio del Castillo",
    department: "Business Development",
  },
  {
    id: 176,
    fullName: "Coop Dibner",
    avatar: "https://robohash.org/hicquaeratmaxime.png?size=50x50&set=set1",
    university: "Maasai Mara University",
    department: "Research and Development",
  },
  {
    id: 177,
    fullName: "Roddy Legrice",
    avatar:
      "https://robohash.org/exercitationemlaboriosamexpedita.png?size=50x50&set=set1",
    university: "University of Groningen",
    department: "Legal",
  },
  {
    id: 178,
    fullName: "Charity De Vuyst",
    avatar:
      "https://robohash.org/sitassumendaperferendis.png?size=50x50&set=set1",
    university: "Bethel College Mishawaka",
    department: "Human Resources",
  },
  {
    id: 179,
    fullName: "Penny Lorence",
    avatar: "https://robohash.org/autemerrornostrum.png?size=50x50&set=set1",
    university: "National University of Laos",
    department: "Legal",
  },
  {
    id: 180,
    fullName: "Reeba Brettor",
    avatar: "https://robohash.org/rerumdistinctionihil.png?size=50x50&set=set1",
    university: "Gifu Women's University",
    department: "Sales",
  },
  {
    id: 181,
    fullName: "Sebastiano Wiles",
    avatar:
      "https://robohash.org/fugitconsequaturmolestias.png?size=50x50&set=set1",
    university: "Academy of Fine Arts",
    department: "Support",
  },
  {
    id: 182,
    fullName: "Onfroi Hammerman",
    avatar: "https://robohash.org/istevelitet.png?size=50x50&set=set1",
    university: "University of Occupational and Environmental Health, Japan",
    department: "Human Resources",
  },
  {
    id: 183,
    fullName: "Curt Benck",
    avatar: "https://robohash.org/optioquistempore.png?size=50x50&set=set1",
    university: "Chamreun University of Poly Technology",
    department: "Business Development",
  },
  {
    id: 184,
    fullName: "Inigo Grisley",
    avatar: "https://robohash.org/officiisprovidentet.png?size=50x50&set=set1",
    university: "Limestone College",
    department: "Services",
  },
  {
    id: 185,
    fullName: "Cob Diem",
    avatar: "https://robohash.org/sedrationeeum.png?size=50x50&set=set1",
    university: "University of Scranton",
    department: "Research and Development",
  },
  {
    id: 186,
    fullName: "Siusan Daddow",
    avatar: "https://robohash.org/etsaepelaboriosam.png?size=50x50&set=set1",
    university: "Vinnica National Technical University",
    department: "Business Development",
  },
  {
    id: 187,
    fullName: "Cathee Perree",
    avatar: "https://robohash.org/quameosfacere.png?size=50x50&set=set1",
    university: "Shenandoah University",
    department: "Research and Development",
  },
  {
    id: 188,
    fullName: "Denni Ault",
    avatar: "https://robohash.org/estisteipsa.png?size=50x50&set=set1",
    university: "Buddhist and Pali University of Sri Lanka",
    department: "Marketing",
  },
  {
    id: 189,
    fullName: "Onofredo Ambrogetti",
    avatar: "https://robohash.org/magnamquirepellat.png?size=50x50&set=set1",
    university: "Universitas Muhammadiyah Sumatra Utara",
    department: "Engineering",
  },
  {
    id: 190,
    fullName: "Eleonore Rehme",
    avatar: "https://robohash.org/maioresetdeleniti.png?size=50x50&set=set1",
    university: "Universidade Federal do Pará",
    department: "Research and Development",
  },
  {
    id: 191,
    fullName: "Anallese Feige",
    avatar: "https://robohash.org/aliquidafuga.png?size=50x50&set=set1",
    university: "Universidad Politécnica de Valencia",
    department: "Human Resources",
  },
  {
    id: 192,
    fullName: "Darn Whotton",
    avatar: "https://robohash.org/illoessequi.png?size=50x50&set=set1",
    university: "Hochschule Bremerhaven",
    department: "Legal",
  },
  {
    id: 193,
    fullName: "Franz Merigeau",
    avatar: "https://robohash.org/odiononsed.png?size=50x50&set=set1",
    university: "Nara University",
    department: "Engineering",
  },
  {
    id: 194,
    fullName: "Cassie Loughan",
    avatar:
      "https://robohash.org/consequaturvoluptatemeos.png?size=50x50&set=set1",
    university: "University of Brighton",
    department: "Services",
  },
  {
    id: 195,
    fullName: "Fons Pfeiffer",
    avatar:
      "https://robohash.org/voluptasassumendaquibusdam.png?size=50x50&set=set1",
    university: "University of Charleston South Carolina",
    department: "Services",
  },
  {
    id: 196,
    fullName: "Shepard Chatto",
    avatar: "https://robohash.org/ametnihilquaerat.png?size=50x50&set=set1",
    university: "Soonchunhyang University",
    department: "Support",
  },
  {
    id: 197,
    fullName: "Sheila Slateford",
    avatar: "https://robohash.org/aliasquianon.png?size=50x50&set=set1",
    university: "Mazandaran University of Science & Technology",
    department: "Accounting",
  },
  {
    id: 198,
    fullName: "Weylin Couchman",
    avatar:
      "https://robohash.org/consequunturmolestiasquidem.png?size=50x50&set=set1",
    university: "National Sanskrit University",
    department: "Product Management",
  },
  {
    id: 199,
    fullName: "Mano Hammant",
    avatar: "https://robohash.org/idcorruptitempora.png?size=50x50&set=set1",
    university: "Irbid National University",
    department: "Support",
  },
  {
    id: 200,
    fullName: "Shelley Kynan",
    avatar: "https://robohash.org/delenitietquos.png?size=50x50&set=set1",
    university: "University of Calgary",
    department: "Human Resources",
  },
];

data.forEach(({avatar,department,fullName,university}) => {
  const cardList = document.querySelector(".cardList");
  cardList.insertAdjacentHTML(
    "beforeend",
    `
    <div class="card">
        <div class="left">
            <div class="imageBox">
                <img src="${avatar}" alt="">
            </div>
        </div>
       <div class="right">
        <div class="name">${fullName}</div>
        <div class="info">
          <div class="university">${university}</div>
          <div class="department">${department}</div>
        </div>
      </div>
    </div>
    `
  );
});
